//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelAlıstırma
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtelBilgi
    {
        public int OtelNo { get; set; }
        public string OtelAdi { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public Nullable<int> YıldızSayisi { get; set; }
        public string Konsept { get; set; }
        public string Sehir { get; set; }
    }
}
